# Raspberry Pi Docker Compose Production Configuration
# This file completely replaces compose.yaml for production deployment on Raspberry Pi
# It does NOT merge with compose.yaml - it's a standalone production configuration
#
# Usage: Copy this to compose.override.yml and run docker compose up -d
# The override will take precedence and provide a complete service definition

services:
  ai-support-bot:
    # Use pre-built production image instead of building locally
    image: ${DOCKER_IMAGE:-sergeyphpdevua/ai-support-bot:latest}
    build: null  # Disable build, use image from Docker Hub
    container_name: ai-support-bot

    # Production ports (only HTTP, no Vite dev server)
    ports:
      - '${APP_PORT:-80}:80'

    # Production volumes - mount specific storage subdirectories to preserve data
    # This approach keeps application code intact while persisting user data
    volumes:
      - storage-app:/var/www/html/storage/app
      - storage-logs:/var/www/html/storage/logs
      - storage-framework-cache:/var/www/html/storage/framework/cache
      - storage-framework-sessions:/var/www/html/storage/framework/sessions
      - storage-framework-views:/var/www/html/storage/framework/views

    # Production environment variables
    environment:
      - APP_NAME=${APP_NAME:-AI Support Bot}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - APP_PORT=80

      # Database - PostgreSQL (External)
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-ai-bot}
      - DB_USERNAME=${DB_USERNAME:-github}
      - DB_PASSWORD=${DB_PASSWORD}

      # Redis connection (External)
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT:-6379}

      # Cache & Session - use Redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

      # Logging
      - LOG_CHANNEL=stack
      - LOG_LEVEL=${LOG_LEVEL:-error}

      # AI & Telegram
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - VITE_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_BOT_NAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAPH_WEBHOOK_URL=${TELEGRAPH_WEBHOOK_URL}

      # Mail
      - MAIL_MAILER=${MAIL_MAILER:-log}

    # No container dependencies - using external services
    depends_on: !reset {}

    # Use host network to connect to external PostgreSQL and Redis
    # !reset removes the networks array from base compose.yaml to avoid conflict with network_mode
    networks: !reset []
    network_mode: host

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# PostgreSQL and Redis are external services

# Named volumes for data persistence
# Mounting specific subdirectories instead of entire storage directory
volumes:
  storage-app:
    driver: local
  storage-logs:
    driver: local
  storage-framework-cache:
    driver: local
  storage-framework-sessions:
    driver: local
  storage-framework-views:
    driver: local
