# Production Docker Compose Override
# This file will be renamed to compose.override.yml on Raspberry Pi during deployment
# It overrides the development settings in compose.yaml with production configuration

services:
  ai-support-bot:
    # Use pre-built production image instead of building locally
    image: ${DOCKER_IMAGE:-sergeyphpdevua/ai-support-bot:latest}
    build: null  # Disable build, use image from Docker Hub

    # Production ports (only HTTP, no Vite dev server)
    ports:
      - '${APP_PORT:-80}:80'

    # Production volumes - persistent data on host
    # IMPORTANT: Only mount specific subdirectories to avoid wiping out the application code
    volumes:
      - /projects/ai-support-bot/data/storage/app:/var/www/html/storage/app
      - /projects/ai-support-bot/data/storage/framework:/var/www/html/storage/framework
      - /projects/ai-support-bot/data/storage/logs:/var/www/html/storage/logs
      - /projects/ai-support-bot/data/database/database.sqlite:/var/www/html/database/database.sqlite
      - /projects/ai-support-bot/data/cache:/var/www/html/bootstrap/cache

    # Production environment variables
    environment:
      - APP_NAME=${APP_NAME:-AI Support Bot}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - APP_PORT=80

      # Database - SQLite
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

      # Redis connection
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      # Cache & Session - use Redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

      # Logging
      - LOG_CHANNEL=stack
      - LOG_LEVEL=${LOG_LEVEL:-error}

      # AI & Telegram
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - VITE_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_BOT_NAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAPH_WEBHOOK_URL=${TELEGRAPH_WEBHOOK_URL}

      # Mail
      - MAIL_MAILER=${MAIL_MAILER:-log}

    # Remove Sail-specific environment variables
    depends_on:
      - redis

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Remove PostgreSQL in production (using SQLite instead)
  pgsql:
    image: null
    restart: "no"
    deploy:
      replicas: 0

  # Keep Redis but with production settings
  redis:
    restart: unless-stopped
    ports: []  # Don't expose Redis port externally
    volumes:
      - /projects/ai-support-bot/data/redis:/data
    command: redis-server --appendonly yes
