# Raspberry Pi Docker Compose Override
# This file will be copied to compose.override.yml on Raspberry Pi during deployment
# It overrides the development settings in compose.yaml with Raspberry Pi production configuration

services:
  ai-support-bot:
    # Use pre-built production image instead of building locally
    image: ${DOCKER_IMAGE:-sergeyphpdevua/ai-support-bot:latest}
    build: null  # Disable build, use image from Docker Hub

    # Production ports (only HTTP, no Vite dev server)
    ports:
      - '${APP_PORT:-80}:80'

    # Production volumes - use named volumes for data persistence
    # Named volumes preserve container data without wiping out application files
    volumes:
      - database-data:/var/www/html/database
      - storage-data:/var/www/html/storage

    # Production environment variables
    environment:
      - APP_NAME=${APP_NAME:-AI Support Bot}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - APP_PORT=80

      # Database - SQLite
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

      # Redis connection
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      # Cache & Session - use Redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

      # Logging
      - LOG_CHANNEL=stack
      - LOG_LEVEL=${LOG_LEVEL:-error}

      # AI & Telegram
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - VITE_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_BOT_NAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAPH_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAPH_WEBHOOK_URL=${TELEGRAPH_WEBHOOK_URL}

      # Mail
      - MAIL_MAILER=${MAIL_MAILER:-log}

    # Remove Sail-specific environment variables
    depends_on:
      - redis

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# PostgreSQL removed in production (using SQLite instead)

  # Keep Redis but with production settings
  redis:
    restart: unless-stopped
    ports: []  # Don't expose Redis port externally
    volumes:
      - redis-data:/data  # Use Docker named volume
    command: redis-server --appendonly yes

# Named volumes for data persistence
volumes:
  database-data:
    driver: local
  storage-data:
    driver: local
  redis-data:
    driver: local
